In [2]:
import torch
import numpy as np

In [26]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]])
print(t)
ft = torch.FloatTensor(t)
print(ft.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
torch.Size([3, 2, 3])


In [27]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(t)
ft = torch.FloatTensor(t)
print(ft.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
torch.Size([2, 2, 3])


In [29]:
print(ft.view([-1,3])) #ft라는 텐서를 (?,3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [30]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
