<a href="https://colab.research.google.com/github/Pulsar-kkaturi/DL-Education/blob/master/Python_Basic/python_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이썬 기초문법 2 - 흐름제어와 함수

# 1. if 문

* 조건에 따라 분기 시켜 실행

In [1]:
x = 11
if x > 10:
    print('x is ') # ... (A1)
    print('        larger than 10.') # ... (A2)
else:
    print('x is smaller than 11') # ... (B1) 

x is 
        larger than 10.


* if 다음에 조건이 맞으면 실행되고, 조건이 틀릴시 else 다음 결과가 출력된다.

In [2]:
print(x > 10)
print(type(x > 10))

True
<class 'bool'>


**[비교연산자]**
* a=b : a와 b가 같다.
* a > b : a가 b보다 크다.
* a >= : a가 b 이상이다.
* a != b : a와 b가 다르다

In [3]:
# 여러 조건 사용시, and(그리고), or(또는) 사용
x = 15
if 10 <= x and x <= 20:
  print('x is between 10 and 20')

x is between 10 and 20


# 2. for 문

* 연산을 반복하고 싶을 때 사용

In [4]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [5]:
# range 함수 사용법
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


In [8]:
# enumerate 함수 사용법
num = [2, 4, 6, 8, 10]
for i, i_ in enumerate(num):
    i_ = i_ + i
print(num)

[2, 4, 6, 8, 10]


# 3. 벡터와 행렬

In [9]:
[1, 2] + [1, 2]

[1, 2, 1, 2]

In [10]:
# 벡터(행렬)을 만들어주는 라이브러리 - 수학연산 라이브러리 Numpy
import numpy as np

In [11]:
x = np.array([1,2,3])
y = np.array([2,2,2])
print(x + y)

[3 4 5]


In [12]:
print(type(x))

<class 'numpy.ndarray'>


In [13]:
# 2차원 행렬
a = [[0,0,0,0,0], [0,0,1,0,0], [0,1,1,1,0], [0,0,1,0,0], [0,0,0,0,0]]
print(type(a))

<class 'list'>


In [14]:
a_vector = np.array(a)
print(type(a_vector))

<class 'list'>


In [17]:
print(a_vector * 2)
print(a_vector + 1)

[[0 0 0 0 0]
 [0 0 2 0 0]
 [0 2 2 2 0]
 [0 0 2 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 2 1 1]
 [1 2 2 2 1]
 [1 1 2 1 1]
 [1 1 1 1 1]]


* 슬라이싱: 행렬에서 특정 부분만 잘라낼때 사용

In [18]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


## 4. 함수

* 자주 반복되는 코드를 함수로 만들면 언제든 사용할 수 있다!

In [19]:
def my_func1():
    print('Hi!')
# 함수 my_func1()의 정의는 여기까지
my_func1() # 함수를 실행

Hi!


In [20]:
def my_func2(a, b):
    c = a + b
    return c


my_func2(1, 2)

3